[package]
name = "ebnsf"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
pest = "2.7.15"
pest_derive = "2.7.15"
railroad = { version = "0.3.2", features = ["resvg"] }
